# For more information: https://laravel.com/docs/sail
version: "3"
services:
  app:
    build:
      context: ./docker/8.0/php
      dockerfile: Dockerfile
      args:
        - TZ="Asia/Tokyo"
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./:/var/www/html
      - ./docker/8.0/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
  web:
    build:
      context: .
      dockerfile: ./docker/8.0/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - ${WEB_PORT-80}:80
    volumes:
      - ./:/var/www/html
      - ./docker/8.0/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  # laravel.test:
  #   build:
  #     context: ./docker/8.0
  #     dockerfile: Dockerfile
  #     args:
  #       WWWGROUP: "${WWWGROUP}"
  #   image: sail-8.0/app
  #   ports:
  #     - "${APP_PORT:-80}:80"
  #   environment:
  #     WWWUSER: "${WWWUSER}"
  #     LARAVEL_SAIL: 1
  #   volumes:
  #     - ".:/var/www/html"
  #   networks:
  #     - sail
  #   depends_on:
  #     - mysql
  #     - redis
  # - selenium
  # selenium:
  #     image: 'selenium/standalone-chrome'
  #     volumes:
  #         - '/dev/shm:/dev/shm'
  #     networks:
  #         - sail
  #     depends_on:
  #         - laravel.test
  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "sailmysql:/var/lib/mysql"
    networks:
      - sail
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sailredis:/data"
    networks:
      - sail
  # memcached:
  #     image: 'memcached:alpine'
  #     ports:
  #         - '11211:11211'
  #     networks:
  #         - sail
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
